# E-Commerce Sales & Customer Analytics

## 1. Business Problem

The company has accumulated e-commerce transaction data but does not have
a structured analysis of its sales, profitability, customer behavior,
product performance, and regional performance.

The objective of this project is to analyze the transaction data using
Python and identify meaningful business patterns that can support
data-driven decision making.

## 2. Business Objectives

1. Analyze overall sales and profit performance.
2. Identify top-performing products and categories.
3. Analyze regional and city-level performance.
4. Understand customer purchasing behavior.
5. Analyze sales channels and payment methods.
6. Analyze the relationship between discounts and profit.
7. Identify monthly sales and profit trends.
8. Generate data-driven business recommendations.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\shivp\Desktop\E-Commerce Sales & Customer Analytics\Ecommerce_Sales_Analytics_Uncleaned.csv")

In [3]:
df.head()

,Order_ID,Order_Date,Customer_ID,City,Region,Category,Product,Quantity,Unit_Price,Discount,Sales,Profit,Payment_Method,Sales_Channel,Customer_Type,Customer_Rating,Shipping_Type
0,ORD100000,2025-04-13,CUST1375,Ahmedabad,West,Electronics,Headphones,3,4908.52,0.00,14725.56,5302.90,Net Banking,Mobile App,Returning,5.0,Express
1,ORD100001,2025-12-15,CUST1144,Kolkata,East,Electronics,Tablet,3,29719.29,0.00,89157.87,22571.48,Credit Card,Mobile App,Returning,4.0,Standard
2,ORD100002,2025-09-28,CUST1398,Pune,West,Home & Kitchen,Cookware Set,1,10312.62,0.10,9281.36,1133.62,UPI,Mobile App,New,4.0,Standard
3,ORD100003,2025-04-17,CUST1037,Lucknow,North,Home & Kitchen,Office Chair,4,17857.59,0.05,67858.84,15913.54,Debit Card,Website,Returning,4.0,Express
4,ORD100004,2025-03-13,CUST1228,Bengaluru,South,Fashion,T-Shirt,2,1603.71,0.05,3047.05,452.88,Cash on Delivery,Marketplace,New,4.0,Same Day

In [4]:
df.shape

(5008, 17)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5008 entries, 0 to 5007
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         5008 non-null   object
 1   Order_Date       5008 non-null   object
 2   Customer_ID      5008 non-null   object
 3   City             4993 non-null   object
 4   Region           5008 non-null   object
 5   Category         5008 non-null   object
 6   Product          5008 non-null   object
 7   Quantity         5008 non-null   int64
 8   Unit_Price       5008 non-null   float64
 9   Discount         4998 non-null   float64
 10  Sales            5008 non-null   float64
 11  Profit           5008 non-null   float64
 12  Payment_Method   5003 non-null   object
 13  Sales_Channel    5008 non-null   object
 14  Customer_Type    5008 non-null   object
 15  Customer_Rating  5003 non-null   float64
 16  Shipping_Type    5008 non-null   object
dtypes: float64(5), int64(1), object(11)
memory usage: 665.3+ KB

In [6]:
df.describe()

,Quantity,Unit_Price,Discount,Sales,Profit,Customer_Rating
count,5008.000000,5008.000000,4998.000000,5008.000000,5008.000000,5003.000000
mean,2.327676,10936.822806,0.099070,23178.995673,5739.455323,4.009394
std,1.350741,17620.681023,0.069847,44945.250031,11737.657136,1.021222
min,0.000000,250.020000,0.000000,230.150000,40.330000,1.000000
25%,1.000000,1607.860000,0.050000,2724.062500,651.762500,4.000000
50%,2.000000,3855.315000,0.100000,6825.630000,1639.915000,4.000000
75%,3.000000,10522.355000,0.150000,20264.627500,5058.580000,5.000000
max,6.000000,94939.650000,0.350000,475277.540000,152755.810000,5.000000

In [7]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
City               15
Region              0
Category            0
Product             0
Quantity            0
Unit_Price          0
Discount           10
Sales               0
Profit              0
Payment_Method      5
Sales_Channel       0
Customer_Type       0
Customer_Rating     5
Shipping_Type       0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(8)

## Data Understanding Summary

- The dataset contains 5,008 transaction records and 17 columns.
- Order_Date is currently stored as an object and should be converted to datetime.
- Missing values are present in City, Discount, Payment_Method, and Customer_Rating.
- The dataset contains 8 duplicate records that require investigation.
- Quantity contains a minimum value of 0, which may represent an invalid transaction.
- Discount contains values up to 35%, which should be investigated for validity.
- Sales and Profit have relatively large differences between their median and maximum values, suggesting potentially skewed distributions.
- Customer_Rating ranges from 1 to 5 and contains 5 missing values.

In [9]:
#Duplicate records
df[df.duplicated()]

,Order_ID,Order_Date,Customer_ID,City,Region,Category,Product,Quantity,Unit_Price,Discount,Sales,Profit,Payment_Method,Sales_Channel,Customer_Type,Customer_Rating,Shipping_Type
5000,ORD103406,2025-09-17,CUST1079,Chennai,South,Fashion,T-Shirt,1,826.08,0.05,784.78,218.42,Cash on Delivery,Website,Returning,4.0,Standard
5001,ORD100757,2025-06-22,CUST1481,Mumbai,West,Books,Python Book,4,1157.36,0.15,3935.02,1056.65,UPI,Marketplace,Returning,4.0,Same Day
5002,ORD103624,2025-10-17,CUST1164,Pune,West,Fashion,Jacket,1,6235.64,0.20,4988.51,669.71,Debit Card,Website,Returning,4.0,Standard
5003,ORD104544,2025-03-28,CUST1320,Kolkata,East,Sports,Dumbbells,1,4872.67,0.10,4385.40,825.46,UPI,Marketplace,New,4.0,Standard
5004,ORD103235,2025-11-08,CUST1257,Ahmedabad,West,Electronics,Smartphone,1,20995.52,0.25,15746.64,2317.18,Debit Card,Website,Returning,3.0,Standard
5005,ORD101868,2025-12-28,CUST1360,Kolkata,East,Fashion,Shoes,1,6843.96,0.10,6159.56,1756.80,Cash on Delivery,Website,Returning,5.0,Standard
5006,ORD102916,2025-04-08,CUST1797,Delhi,North,Books,Data Analytics Book,1,1911.96,0.05,1816.36,366.45,Net Banking,Mobile App,New,5.0,Express
5007,ORD103335,2025-09-15,CUST1331,Bengaluru,South,Electronics,Tablet,2,38792.30,0.10,69826.14,20022.88,UPI,Website,New,5.0,Same Day

In [10]:
#records with 0 quantity
df[df['Quantity'] == 0]

,Order_ID,Order_Date,Customer_ID,City,Region,Category,Product,Quantity,Unit_Price,Discount,Sales,Profit,Payment_Method,Sales_Channel,Customer_Type,Customer_Rating,Shipping_Type
1300,ORD101300,2025-08-10,CUST1330,Delhi,North,Electronics,Smartwatch,0,11075.36,0.00,22150.72,4475.67,Cash on Delivery,Website,Returning,3.0,Standard
1593,ORD101593,2025-07-14,CUST1296,Pune,West,Fashion,Backpack,0,2304.28,0.20,1843.42,482.19,Debit Card,Website,Returning,4.0,Standard
1765,ORD101765,2025-03-20,CUST1080,Pune,West,Books,Business Book,0,639.25,0.10,1150.65,360.53,Cash on Delivery,Marketplace,New,4.0,Express
4218,ORD104218,2025-02-01,CUST1051,Bengaluru,South,Books,Novel,0,672.04,0.05,1276.88,272.21,Credit Card,Mobile App,New,4.0,Express

In [11]:
#Dicount Distribution
df['Discount'].value_counts(dropna=False).sort_index()

Discount
0.00     897
0.05    1012
0.10    1340
0.15    1026
0.20     492
0.25     226
0.35       5
NaN       10
Name: count, dtype: int64

In [12]:
df[df['City'].isnull()]

,Order_ID,Order_Date,Customer_ID,City,Region,Category,Product,Quantity,Unit_Price,Discount,Sales,Profit,Payment_Method,Sales_Channel,Customer_Type,Customer_Rating,Shipping_Type
460,ORD100460,2025-12-15,CUST1242,NaN,West,Home & Kitchen,Office Chair,4,10966.10,0.10,39477.96,14636.09,Credit Card,Website,Returning,4.0,Standard
475,ORD100475,2025-12-07,CUST1364,NaN,South,Electronics,Tablet,2,23489.74,0.15,39932.56,7076.46,Net Banking,Marketplace,Returning,5.0,Standard
508,ORD100508,2025-06-28,CUST1738,NaN,North,Electronics,Laptop,4,65660.17,0.00,262640.68,36515.00,Debit Card,Website,New,3.0,Express
627,ORD100627,2025-03-11,CUST1420,NaN,South,Books,Exam Guide,4,1046.14,0.10,3766.10,491.52,Net Banking,Mobile App,Returning,4.0,Standard
640,ORD100640,2025-05-21,CUST1341,NaN,North,Electronics,Headphones,2,10625.38,0.05,20188.22,2818.18,UPI,Website,New,4.0,Standard
884,ORD100884,2025-08-02,CUST1686,NaN,North,Electronics,Smartwatch,1,13136.26,0.00,13136.26,2414.22,UPI,Website,New,5.0,Express
2226,ORD102226,2025-06-13,CUST1443,NaN,West,Sports,Dumbbells,2,3095.39,0.15,5262.16,716.10,Credit Card,Website,Returning,5.0,Standard
2763,ORD102763,2025-05-26,CUST1403,NaN,West,Fashion,T-Shirt,3,437.79,0.15,1116.36,373.74,Credit Card,Website,Returning,4.0,Same Day
3267,ORD103267,2025-02-08,CUST1185,NaN,West,Sports,Yoga Mat,2,2286.12,0.05,4343.63,1422.74,Debit Card,Website,New,5.0,Express
3405,ORD103405,2025-02-14,CUST1512,NaN,West,Fashion,Backpack,2,1235.26,0.00,2470.52,866.44,Net Banking,Mobile App,Returning,5.0,Same Day
3614,ORD103614,2025-05-25,CUST1509,NaN,South,Sports,Dumbbells,2,2061.06,0.15,3503.80,809.01,Net Banking,Website,New,1.0,Standard
4045,ORD104045,2025-03-23,CUST1422,NaN,North,Books,Exam Guide,1,749.22,0.20,599.38,129.27,Debit Card,Marketplace,Returning,5.0,Standard
4121,ORD104121,2025-02-23,CUST1687,NaN,South,Books,Python Book,3,984.53,0.15,2510.55,417.48,Debit Card,Website,Returning,3.0,Standard
4264,ORD104264,2025-05-06,CUST1553,NaN,North,Electronics,Headphones,1,5234.52,0.00,5234.52,1671.12,Credit Card,Mobile App,New,4.0,Standard
4674,ORD104674,2025-06-22,CUST1200,NaN,East,Electronics,Laptop,6,63219.21,0.00,379315.26,132524.41,Net Banking,Marketplace,Returning,5.0,Standard

In [13]:
#Payment method Distribution

df['Payment_Method'].value_counts()

Payment_Method
Cash on Delivery    1074
Net Banking          994
Debit Card           991
Credit Card          988
UPI                  956
Name: count, dtype: int64

In [14]:
#Customer rating distribution

df['Customer_Rating'].value_counts()

Customer_Rating
4.0    1938
5.0    1869
3.0     707
2.0     352
1.0     137
Name: count, dtype: int64

In [15]:
#Date Invetigation

df['Order_Date'].head(10)

0    2025-04-13
1    2025-12-15
2    2025-09-28
3    2025-04-17
4    2025-03-13
5    2025-07-08
6    2025-01-21
7    2025-04-13
8    2025-05-02
9    2025-08-03
Name: Order_Date, dtype: object

# Data Cleaning

In [16]:
#Chaning DataType of Order_Date column
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [17]:
df['Order_Date'].dtype

dtype('<M8[ns]')

In [18]:
df.isnull().sum()/5008*100

Order_ID           0.000000
Order_Date         0.000000
Customer_ID        0.000000
City               0.299521
Region             0.000000
Category           0.000000
Product            0.000000
Quantity           0.000000
Unit_Price         0.000000
Discount           0.199681
Sales              0.000000
Profit             0.000000
Payment_Method     0.099840
Sales_Channel      0.000000
Customer_Type      0.000000
Customer_Rating    0.099840
Shipping_Type      0.000000
dtype: float64

In [19]:
#Handlig The missing values

df.dropna(subset=['City', 'Discount', 'Payment_Method', 'Customer_Rating'], inplace=True)

In [20]:
df.isnull().sum()

Order_ID           0
Order_Date         0
Customer_ID        0
City               0
Region             0
Category           0
Product            0
Quantity           0
Unit_Price         0
Discount           0
Sales              0
Profit             0
Payment_Method     0
Sales_Channel      0
Customer_Type      0
Customer_Rating    0
Shipping_Type      0
dtype: int64

- Handeling the duplicate records

In [21]:
df.duplicated().sum()

np.int64(8)

In [22]:
# Deleting the Duplicate records from the dataset
df.drop_duplicates(inplace=True)

In [23]:
df.shape

(4965, 17)

In [24]:
df.describe()

,Order_Date,Quantity,Unit_Price,Discount,Sales,Profit,Customer_Rating
count,4965,4965.000000,4965.000000,4965.000000,4965.000000,4965.000000,4965.000000
mean,2025-07-01 14:44:00.725075712,2.328298,10898.448975,0.099094,23034.415980,5702.663315,4.007452
min,2025-01-01 00:00:00,0.000000,250.020000,0.000000,230.150000,40.330000,1.000000
25%,2025-04-03 00:00:00,1.000000,1608.200000,0.050000,2725.220000,652.010000,4.000000
50%,2025-06-28 00:00:00,2.000000,3851.520000,0.100000,6835.630000,1642.810000,4.000000
75%,2025-10-02 00:00:00,3.000000,10499.200000,0.150000,20219.820000,5055.840000,5.000000
max,2025-12-31 00:00:00,6.000000,94939.650000,0.350000,475277.540000,152755.810000,5.000000
std,NaN,1.350596,17561.488480,0.069859,44532.063194,11595.011623,1.021991

In [25]:
df[df['Quantity'] == 0]

,Order_ID,Order_Date,Customer_ID,City,Region,Category,Product,Quantity,Unit_Price,Discount,Sales,Profit,Payment_Method,Sales_Channel,Customer_Type,Customer_Rating,Shipping_Type
1300,ORD101300,2025-08-10,CUST1330,Delhi,North,Electronics,Smartwatch,0,11075.36,0.00,22150.72,4475.67,Cash on Delivery,Website,Returning,3.0,Standard
1593,ORD101593,2025-07-14,CUST1296,Pune,West,Fashion,Backpack,0,2304.28,0.20,1843.42,482.19,Debit Card,Website,Returning,4.0,Standard
1765,ORD101765,2025-03-20,CUST1080,Pune,West,Books,Business Book,0,639.25,0.10,1150.65,360.53,Cash on Delivery,Marketplace,New,4.0,Express
4218,ORD104218,2025-02-01,CUST1051,Bengaluru,South,Books,Novel,0,672.04,0.05,1276.88,272.21,Credit Card,Mobile App,New,4.0,Express

In [26]:
# Deleting the rows which have the Quantity = 0
df = df[df['Quantity'] != 0]

In [27]:
df.shape

(4961, 17)

In [28]:
df['Discount'].unique()

array([0.  , 0.1 , 0.05, 0.15, 0.2 , 0.25, 0.35])

In [29]:
df['Customer_Rating'].unique()

array([5., 4., 3., 2., 1.])

In [30]:
df['Quantity'].unique()

array([3, 1, 4, 2, 5, 6])

In [31]:
df.isnull().sum()

Order_ID           0
Order_Date         0
Customer_ID        0
City               0
Region             0
Category           0
Product            0
Quantity           0
Unit_Price         0
Discount           0
Sales              0
Profit             0
Payment_Method     0
Sales_Channel      0
Customer_Type      0
Customer_Rating    0
Shipping_Type      0
dtype: int64

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df['Month'] = df['Order_Date'].dt.month

In [34]:
# Total sales by sales channel

df.groupby("Sales_Channel")['Sales'].sum()

Sales_Channel
Marketplace    39719821.30
Mobile App     38020466.79
Mobile app       219399.90
Website        36290519.25
website           89246.43
Name: Sales, dtype: float64

- In Sales channel I found some Inconsistency.

In [35]:
# Lets Fix IT

In [36]:
df['Sales_Channel'].unique()

array(['Mobile App', 'Website', 'Marketplace', 'Mobile app', 'website'],
      dtype=object)

In [37]:
df['Sales_Channel'] = df['Sales_Channel'].replace({'Mobile app': 'Mobile App' , 'website':'Website'})

In [38]:
df['Sales_Channel'].unique()

array(['Mobile App', 'Website', 'Marketplace'], dtype=object)

## Data Cleaning Summary

- Converted Order_Date to datetime.
- Removed rows with missing values.
- Removed duplicate records.
- Removed records where Quantity was 0.
- Verified that no missing values remain.
- Verified that no duplicate records remain.
- Final dataset contains 4,961 rows and 17 columns.

In [39]:
# Now saving the Cleaned file

df.to_csv('Ecommerce_Sales_Analytics_Cleaned.csv', index=False)

In [40]:
df.shape

(4961, 18)